name: Deno Edge Functions

on:
  push:
    branches: ["main"]
    paths:
      - 'supabase/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'supabase/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check supabase/

      - name: Run linter
        run: deno lint supabase/functions/

      - name: Type-check edge functions
        run: deno check supabase/functions/*/index.ts
